baseURL = "https://blog.narsk.sbs/"
theme = "introduction"
title = "Jovan Hsu"
preserveTaxonomyNames = true
DefaultContentLanguage = "zh"

[languages]
[languages.zh]
languageName = "中文"
languageCode = "zh-cn"
contentDir = "content/zh"
weight = 1
title = "Jovan Hsu"

[languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 2
title = "Jovan Hsu"

[params]
    themeStyle = "light"
    favicon = "/img/fav.ico"
    showMenu = true
    showRSSButton = false
    fadeIn = true
    fadeInIndex = false
    dateFormat = "2006-01-02"
    email = "hello@narsk.sbs"

    [params.home]
        introHeight = "medium"
        showLatest = false
        showAllPosts = false
        allPostsArchiveFormat = true
        numberOfProjectsToShow = 0
        localTime = true
        timeZone = "Asia/Shanghai"
        timeFormat = "zh-CN"

    [[params.social]]
        url = "https://github.com/JovanHsu"
        icon = "github"
        icon_pack = "fab"

    [[params.social]]
        url = "https://twitter.com/"
        icon = "twitter"
        icon_pack = "fab"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        style = "solarized-dark"
        tabWidth = 4

[taxonomies]
    tag = "tags"
    series = "series"
